services:
  server: 
    container_name: server
    build:
      context: .
    env_file:
      - .env
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on: 
      - postgres
    restart: always
    networks: 
      - backend

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks: 
      - backend

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks: 
      - backend

volumes:
  pgdata:

networks: 
  backend:
    driver: bridge  
