services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      POSTGRES_CONNECTION: psql
      POSTGRES_HOST: ${DB_HOST2} 
      POSTGRES_DB: wb_test  
      POSTGRES_USER: ${DB_USERNAME2} 
      POSTGRES_PASSWORD: ${DB_PASSWORD2}
      POSTGRES_PORT: ${DB_PORT2}

